import type { Metadata } from 'next'
import { headers } from 'next/headers'
import { notFound } from 'next/navigation'
import { ReportView } from '@/components/report/report-view'
import { DEMO_SLUG } from '@/lib/demo/data'
import { countPublicView } from '@/lib/report/store'
import type { ReportView as ReportViewData } from '@/lib/report/types'
import { log } from '@/lib/log'
import { loadPublicReport } from './data'

const BOT_PATTERN = /bot|crawler|spider|preview|facebookexternalhit|slackbot|discordbot|whatsapp|embedly|quora|pinterest|vkshare|w3c_validator/i

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params
  const report = await loadPublicReport(slug)
  if (!report) return { title: 'Report not found', robots: { index: false } }

  const title = `${report.brandName} brand guidelines`
  const description = report.summary.description?.slice(0, 200) || `Colours, typography and voice for ${report.domain}, generated by BrandLens.`
  return {
    title,
    description,
    // Reports describe third-party brands: shareable by link, but not indexed
    robots: { index: false, follow: false },
    openGraph: { title, description, type: 'article' },
    twitter: { card: 'summary_large_image', title, description },
  }
}

export default async function PublicReportPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const report = await loadPublicReport(slug)
  if (!report) notFound()

  const userAgent = (await headers()).get('user-agent') ?? ''
  if (slug !== DEMO_SLUG && !BOT_PATTERN.test(userAgent)) {
    countPublicView(slug).catch(error => log.error('report.view_count_failed', error, { slug }))
  }

  const view: ReportViewData = {
    id: report.id,
    status: 'completed',
    report,
    isOwner: false,
    isPublic: true,
    regenerationsLeft: 0,
  }

  return <ReportView view={view} context="public" />
}
