/**
 * Render the brand board PNG by drawing directly on a canvas.
 *
 * Every value comes from a third-party website or a model, so nothing is ever
 * parsed as HTML (fixes the stored XSS in A4): text is painted with fillText
 * and colors are re-validated as 6-digit hex. Drawing directly also avoids
 * html2canvas, which cannot parse the lab()/oklch() colors modern CSS reports.
 */

import type { BrandReport } from '../extractors/types'
import { readableTextOn, safeHex } from '../color-contrast'

const WIDTH = 1200
const PADDING = 60
const SCALE = 2
const INK = '#0f172a'
const MUTED = '#475569'
const RULE = '#e2e8f0'
const SANS = 'system-ui, -apple-system, "Segoe UI", sans-serif'

export function fileSlug(name: string) {
  return name.normalize('NFKD').replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-|-$/g, '').toLowerCase().slice(0, 60) || 'brand'
}

/** Font names are used inside a canvas font string; keep them inert */
function fontFamily(name: string) {
  return `"${name.replace(/["\\<>;{}]/g, '')}", ${SANS}`
}

/** Shorten text with an ellipsis until it fits `maxWidth` */
function fit(ctx: CanvasRenderingContext2D, text: string, maxWidth: number): string {
  if (ctx.measureText(text).width <= maxWidth) return text
  let end = text.length
  while (end > 0 && ctx.measureText(`${text.slice(0, end)}…`).width > maxWidth) end--
  return `${text.slice(0, end)}…`
}

function roundRect(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number) {
  ctx.beginPath()
  ctx.moveTo(x + r, y)
  ctx.arcTo(x + w, y, x + w, y + h, r)
  ctx.arcTo(x + w, y + h, x, y + h, r)
  ctx.arcTo(x, y + h, x, y, r)
  ctx.arcTo(x, y, x + w, y, r)
  ctx.closePath()
}

function sectionLabel(ctx: CanvasRenderingContext2D, text: string, x: number, y: number) {
  ctx.fillStyle = MUTED
  ctx.font = `600 14px ${SANS}`
  ctx.fillText(text.toUpperCase(), x, y)
}

function draw(ctx: CanvasRenderingContext2D, report: BrandReport, height: number) {
  const column = (WIDTH - PADDING * 3) / 2
  ctx.fillStyle = '#ffffff'
  ctx.fillRect(0, 0, WIDTH, height)
  ctx.textBaseline = 'alphabetic'

  // Title
  ctx.fillStyle = INK
  ctx.font = `700 48px ${SANS}`
  ctx.fillText(fit(ctx, report.brandName, WIDTH - PADDING * 2), PADDING, PADDING + 48)
  ctx.fillStyle = MUTED
  ctx.font = `400 18px ${SANS}`
  ctx.fillText('Brand Guidelines', PADDING, PADDING + 82)

  // Colors
  const top = PADDING + 140
  sectionLabel(ctx, 'Color Palette', PADDING, top)
  report.colors.colors.slice(0, 6).forEach((color, index) => {
    const hex = safeHex(color.hex, '#000000')
    const x = PADDING + (index % 3) * 130
    const y = top + 20 + Math.floor(index / 3) * 150
    ctx.fillStyle = hex
    roundRect(ctx, x, y, 110, 90, 12)
    ctx.fill()
    ctx.strokeStyle = RULE
    ctx.stroke()
    ctx.fillStyle = INK
    ctx.font = `600 13px ${SANS}`
    ctx.fillText(hex.toUpperCase(), x, y + 110)
    ctx.fillStyle = MUTED
    ctx.font = `400 12px ${SANS}`
    ctx.fillText(color.role, x, y + 128)
  })

  // Typography
  const typeX = PADDING * 2 + column
  sectionLabel(ctx, 'Typography', typeX, top)
  const fonts = report.typography.fonts.slice(0, 3)
  if (fonts.length === 0) {
    ctx.fillStyle = MUTED
    ctx.font = `400 16px ${SANS}`
    ctx.fillText('System fonts', typeX, top + 40)
  }
  fonts.forEach((font, index) => {
    const y = top + 60 + index * 90
    ctx.fillStyle = INK
    ctx.font = `700 34px ${fontFamily(font.name)}`
    ctx.fillText('AaBbCc', typeX, y)
    ctx.fillStyle = MUTED
    ctx.font = `400 15px ${SANS}`
    ctx.fillText(fit(ctx, `${font.name} · ${font.role}`, column), typeX, y + 26)
  })

  // Voice
  const traits = report.tone.traits.slice(0, 6)
  const voiceTop = top + 340
  if (traits.length > 0) {
    ctx.fillStyle = RULE
    ctx.fillRect(PADDING, voiceTop - 30, WIDTH - PADDING * 2, 1)
    sectionLabel(ctx, 'Brand Voice', PADDING, voiceTop)
    const primary = safeHex(report.colors.colors.find(c => c.role === 'primary')?.hex, '#4338ca')
    let x = PADDING
    let y = voiceTop + 20
    ctx.font = `600 15px ${SANS}`
    for (const trait of traits) {
      const label = fit(ctx, trait, 300)
      const width = ctx.measureText(label).width + 32
      if (x + width > WIDTH - PADDING) {
        x = PADDING
        y += 50
      }
      ctx.fillStyle = primary
      roundRect(ctx, x, y, width, 38, 19)
      ctx.fill()
      ctx.fillStyle = readableTextOn(primary)
      ctx.fillText(label, x + 16, y + 24)
      x += width + 12
    }
  }

  ctx.fillStyle = MUTED
  ctx.font = `400 12px ${SANS}`
  ctx.textAlign = 'center'
  ctx.fillText(`Generated by BrandLens · ${new Date().toLocaleDateString()}`, WIDTH / 2, height - PADDING / 2)
  ctx.textAlign = 'start'
}

export async function downloadBrandBoard(report: BrandReport): Promise<void> {
  const height = report.tone.traits.length > 0 ? 760 : 640
  const canvas = document.createElement('canvas')
  canvas.width = WIDTH * SCALE
  canvas.height = height * SCALE
  const ctx = canvas.getContext('2d')
  if (!ctx) throw new Error('Canvas is not available')
  ctx.scale(SCALE, SCALE)

  // Give brand web fonts that the page already loaded a chance to be used
  await document.fonts?.ready

  draw(ctx, report, height)

  const blob = await new Promise<Blob | null>(resolve => canvas.toBlob(resolve, 'image/png'))
  if (!blob) throw new Error('Could not encode the brand board')
  const url = URL.createObjectURL(blob)
  try {
    const link = document.createElement('a')
    link.download = `${fileSlug(report.brandName)}-brand-board.png`
    link.href = url
    link.click()
  } finally {
    setTimeout(() => URL.revokeObjectURL(url), 1000)
  }
}
