/**
 * Render the brand board PNG.
 *
 * Every value comes from a third-party website or a model, so the board is
 * built with DOM APIs and textContent only: nothing is ever parsed as HTML
 * (fixes the stored XSS in A4). Colours are re-validated as 6-digit hex.
 */

import type { BrandReport } from '../extractors/types'
import { readableTextOn, safeHex } from '../color-contrast'

type Styles = Partial<CSSStyleDeclaration>

function el<K extends keyof HTMLElementTagNameMap>(tag: K, styles: Styles = {}, text?: string): HTMLElementTagNameMap[K] {
  const node = document.createElement(tag)
  Object.assign(node.style, styles)
  if (text !== undefined) node.textContent = text
  return node
}

function heading(text: string) {
  return el('h2', { fontSize: '14px', textTransform: 'uppercase', letterSpacing: '0.1em', color: '#475569', margin: '0 0 16px 0' }, text)
}

/** Font names are used as a CSS value; keep them to a quoted, inert string */
function fontFamily(name: string) {
  return `"${name.replace(/["\\<>;{}]/g, '')}", sans-serif`
}

export function fileSlug(name: string) {
  return name.normalize('NFKD').replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-|-$/g, '').toLowerCase().slice(0, 60) || 'brand'
}

export async function downloadBrandBoard(report: BrandReport): Promise<void> {
  const html2canvas = (await import('html2canvas')).default

  const container = el('div', {
    position: 'fixed',
    left: '-10000px',
    top: '0',
    width: '1200px',
    padding: '60px',
    backgroundColor: '#ffffff',
    fontFamily: 'system-ui, sans-serif',
    color: '#0f172a',
  })
  container.setAttribute('aria-hidden', 'true')

  const title = el('div', { marginBottom: '40px' })
  title.append(
    el('h1', { fontSize: '48px', fontWeight: '700', margin: '0' }, report.brandName),
    el('p', { fontSize: '18px', color: '#475569', marginTop: '8px' }, 'Brand Guidelines')
  )

  const grid = el('div', { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '40px' })

  const palette = el('div')
  const swatches = el('div', { display: 'flex', gap: '12px', flexWrap: 'wrap' })
  for (const color of report.colors.colors.slice(0, 6)) {
    const hex = safeHex(color.hex, '#000000')
    const item = el('div', { textAlign: 'center' })
    const swatch = el('div', { width: '80px', height: '80px', backgroundColor: hex, borderRadius: '12px', marginBottom: '8px', border: '1px solid #e2e8f0' })
    item.append(
      swatch,
      el('p', { fontSize: '12px', fontWeight: '600', margin: '0' }, hex.toUpperCase()),
      el('p', { fontSize: '11px', color: '#475569', margin: '4px 0 0 0', textTransform: 'capitalize' }, color.role)
    )
    swatches.append(item)
  }
  palette.append(heading('Colour Palette'), swatches)

  const type = el('div')
  type.append(heading('Typography'))
  for (const font of report.typography.fonts.slice(0, 3)) {
    const row = el('div', { marginBottom: '16px' })
    row.append(
      el('p', { fontSize: '32px', fontWeight: '700', margin: '0', fontFamily: fontFamily(font.name) }, 'AaBbCc'),
      el('p', { fontSize: '14px', color: '#475569', marginTop: '4px' }, `${font.name} · ${font.role}`)
    )
    type.append(row)
  }
  if (report.typography.fonts.length === 0) {
    type.append(el('p', { fontSize: '14px', color: '#475569' }, 'System fonts'))
  }

  grid.append(palette, type)

  const voice = el('div', { marginTop: '40px', paddingTop: '40px', borderTop: '1px solid #e2e8f0' })
  const traits = el('div', { display: 'flex', gap: '12px', flexWrap: 'wrap' })
  const primary = safeHex(report.colors.colors.find(c => c.role === 'primary')?.hex, '#4338ca')
  for (const trait of report.tone.traits.slice(0, 6)) {
    traits.append(
      el('span', { padding: '8px 16px', backgroundColor: primary, color: readableTextOn(primary), borderRadius: '20px', fontSize: '14px', fontWeight: '600' }, trait)
    )
  }
  if (report.tone.traits.length > 0) voice.append(heading('Brand Voice'), traits)

  const footer = el('p', { marginTop: '40px', textAlign: 'center', color: '#475569', fontSize: '12px' }, `Generated by BrandLens · ${new Date().toLocaleDateString()}`)

  container.append(title, grid, voice, footer)
  document.body.append(container)

  try {
    const canvas = await html2canvas(container, { scale: 2, backgroundColor: '#ffffff', logging: false, useCORS: false })
    const link = document.createElement('a')
    link.download = `${fileSlug(report.brandName)}-brand-board.png`
    link.href = canvas.toDataURL('image/png')
    link.click()
  } finally {
    container.remove()
  }
}
